# Generated by Django 4.2.7 on 2024-04-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='lang',
            new_name='language',
        ),
    ]
